import SCons

# Add the path to the tool to the SCons tool search path
SCons.Tool.DefaultToolpath.insert(0, Dir('../..').abspath)

# Create an environment with the makotemplate tool loaded
env = Environment(tools=['makotemplate'])

# Build a template with the mako builder
data = File('data.yaml')
mako = env.Mako(
    'template.txt',
    'template.txt.mako',
    MAKO_DICTIONARY={'FILE': data.abspath})
env.Depends(mako, data)
